/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as FaturaTelefoneRouteImport } from './routes/fatura.$telefone'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminFaturasRouteImport } from './routes/_authenticated/admin.faturas'
import { Route as AuthenticatedAdminGatewaysRouteImport } from './routes/_authenticated/admin.gateways'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminPagamentosRouteImport } from './routes/_authenticated/admin.pagamentos'
import { Route as AuthenticatedAdminTransacoesRouteImport } from './routes/_authenticated/admin.transacoes'
import { Route as ApiPublicCobrancaRouteImport } from './routes/api/public/cobranca'
import { Route as ApiPublicFaturasRouteImport } from './routes/api/public/faturas'
import { Route as ApiPublicGetLogsRouteImport } from './routes/api/public/get-logs'
import { Route as ApiPublicSetupPropixRouteImport } from './routes/api/public/setup-propix'
import { Route as ApiPublicTestFluxoRouteImport } from './routes/api/public/test-fluxo'
import { Route as ApiPublicTestPropixDiretoRouteImport } from './routes/api/public/test-propix-direto'
import { Route as ApiPublicTestPropixV3RouteImport } from './routes/api/public/test-propix-v3'
import { Route as ApiPublicTestSecretsRouteImport } from './routes/api/public/test-secrets'
import { Route as ApiPublicWebhooksSlugRouteImport } from './routes/api/public/webhooks/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const FaturaTelefoneRoute = FaturaTelefoneRouteImport.update({
  id: '/fatura/$telefone',
  path: '/fatura/$telefone',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaturasRoute =
  AuthenticatedAdminFaturasRouteImport.update({
    id: '/faturas',
    path: '/faturas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGatewaysRoute =
  AuthenticatedAdminGatewaysRouteImport.update({
    id: '/gateways',
    path: '/gateways',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPagamentosRoute =
  AuthenticatedAdminPagamentosRouteImport.update({
    id: '/pagamentos',
    path: '/pagamentos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTransacoesRoute =
  AuthenticatedAdminTransacoesRouteImport.update({
    id: '/transacoes',
    path: '/transacoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicCobrancaRoute = ApiPublicCobrancaRouteImport.update({
  id: '/api/public/cobranca',
  path: '/api/public/cobranca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFaturasRoute = ApiPublicFaturasRouteImport.update({
  id: '/api/public/faturas',
  path: '/api/public/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGetLogsRoute = ApiPublicGetLogsRouteImport.update({
  id: '/api/public/get-logs',
  path: '/api/public/get-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSetupPropixRoute = ApiPublicSetupPropixRouteImport.update({
  id: '/api/public/setup-propix',
  path: '/api/public/setup-propix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestFluxoRoute = ApiPublicTestFluxoRouteImport.update({
  id: '/api/public/test-fluxo',
  path: '/api/public/test-fluxo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestPropixDiretoRoute =
  ApiPublicTestPropixDiretoRouteImport.update({
    id: '/api/public/test-propix-direto',
    path: '/api/public/test-propix-direto',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTestPropixV3Route = ApiPublicTestPropixV3RouteImport.update({
  id: '/api/public/test-propix-v3',
  path: '/api/public/test-propix-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestSecretsRoute = ApiPublicTestSecretsRouteImport.update({
  id: '/api/public/test-secrets',
  path: '/api/public/test-secrets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksSlugRoute = ApiPublicWebhooksSlugRouteImport.update({
  id: '/api/public/webhooks/$slug',
  path: '/api/public/webhooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/fatura/$telefone': typeof FaturaTelefoneRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/faturas': typeof AuthenticatedAdminFaturasRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/transacoes': typeof AuthenticatedAdminTransacoesRoute
  '/api/public/cobranca': typeof ApiPublicCobrancaRoute
  '/api/public/faturas': typeof ApiPublicFaturasRoute
  '/api/public/get-logs': typeof ApiPublicGetLogsRoute
  '/api/public/setup-propix': typeof ApiPublicSetupPropixRoute
  '/api/public/test-fluxo': typeof ApiPublicTestFluxoRoute
  '/api/public/test-propix-direto': typeof ApiPublicTestPropixDiretoRoute
  '/api/public/test-propix-v3': typeof ApiPublicTestPropixV3Route
  '/api/public/test-secrets': typeof ApiPublicTestSecretsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/fatura/$telefone': typeof FaturaTelefoneRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/faturas': typeof AuthenticatedAdminFaturasRoute
  '/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/admin/transacoes': typeof AuthenticatedAdminTransacoesRoute
  '/api/public/cobranca': typeof ApiPublicCobrancaRoute
  '/api/public/faturas': typeof ApiPublicFaturasRoute
  '/api/public/get-logs': typeof ApiPublicGetLogsRoute
  '/api/public/setup-propix': typeof ApiPublicSetupPropixRoute
  '/api/public/test-fluxo': typeof ApiPublicTestFluxoRoute
  '/api/public/test-propix-direto': typeof ApiPublicTestPropixDiretoRoute
  '/api/public/test-propix-v3': typeof ApiPublicTestPropixV3Route
  '/api/public/test-secrets': typeof ApiPublicTestSecretsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/fatura/$telefone': typeof FaturaTelefoneRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/faturas': typeof AuthenticatedAdminFaturasRoute
  '/_authenticated/admin/gateways': typeof AuthenticatedAdminGatewaysRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/pagamentos': typeof AuthenticatedAdminPagamentosRoute
  '/_authenticated/admin/transacoes': typeof AuthenticatedAdminTransacoesRoute
  '/api/public/cobranca': typeof ApiPublicCobrancaRoute
  '/api/public/faturas': typeof ApiPublicFaturasRoute
  '/api/public/get-logs': typeof ApiPublicGetLogsRoute
  '/api/public/setup-propix': typeof ApiPublicSetupPropixRoute
  '/api/public/test-fluxo': typeof ApiPublicTestFluxoRoute
  '/api/public/test-propix-direto': typeof ApiPublicTestPropixDiretoRoute
  '/api/public/test-propix-v3': typeof ApiPublicTestPropixV3Route
  '/api/public/test-secrets': typeof ApiPublicTestSecretsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/$slug': typeof ApiPublicWebhooksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/fatura/$telefone'
    | '/admin/clientes'
    | '/admin/faturas'
    | '/admin/gateways'
    | '/admin/logs'
    | '/admin/pagamentos'
    | '/admin/transacoes'
    | '/api/public/cobranca'
    | '/api/public/faturas'
    | '/api/public/get-logs'
    | '/api/public/setup-propix'
    | '/api/public/test-fluxo'
    | '/api/public/test-propix-direto'
    | '/api/public/test-propix-v3'
    | '/api/public/test-secrets'
    | '/admin/'
    | '/api/public/webhooks/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/fatura/$telefone'
    | '/admin/clientes'
    | '/admin/faturas'
    | '/admin/gateways'
    | '/admin/logs'
    | '/admin/pagamentos'
    | '/admin/transacoes'
    | '/api/public/cobranca'
    | '/api/public/faturas'
    | '/api/public/get-logs'
    | '/api/public/setup-propix'
    | '/api/public/test-fluxo'
    | '/api/public/test-propix-direto'
    | '/api/public/test-propix-v3'
    | '/api/public/test-secrets'
    | '/admin'
    | '/api/public/webhooks/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/fatura/$telefone'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/faturas'
    | '/_authenticated/admin/gateways'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/pagamentos'
    | '/_authenticated/admin/transacoes'
    | '/api/public/cobranca'
    | '/api/public/faturas'
    | '/api/public/get-logs'
    | '/api/public/setup-propix'
    | '/api/public/test-fluxo'
    | '/api/public/test-propix-direto'
    | '/api/public/test-propix-v3'
    | '/api/public/test-secrets'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  FaturaTelefoneRoute: typeof FaturaTelefoneRoute
  ApiPublicCobrancaRoute: typeof ApiPublicCobrancaRoute
  ApiPublicFaturasRoute: typeof ApiPublicFaturasRoute
  ApiPublicGetLogsRoute: typeof ApiPublicGetLogsRoute
  ApiPublicSetupPropixRoute: typeof ApiPublicSetupPropixRoute
  ApiPublicTestFluxoRoute: typeof ApiPublicTestFluxoRoute
  ApiPublicTestPropixDiretoRoute: typeof ApiPublicTestPropixDiretoRoute
  ApiPublicTestPropixV3Route: typeof ApiPublicTestPropixV3Route
  ApiPublicTestSecretsRoute: typeof ApiPublicTestSecretsRoute
  ApiPublicWebhooksSlugRoute: typeof ApiPublicWebhooksSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/fatura/$telefone': {
      id: '/fatura/$telefone'
      path: '/fatura/$telefone'
      fullPath: '/fatura/$telefone'
      preLoaderRoute: typeof FaturaTelefoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faturas': {
      id: '/_authenticated/admin/faturas'
      path: '/faturas'
      fullPath: '/admin/faturas'
      preLoaderRoute: typeof AuthenticatedAdminFaturasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/gateways': {
      id: '/_authenticated/admin/gateways'
      path: '/gateways'
      fullPath: '/admin/gateways'
      preLoaderRoute: typeof AuthenticatedAdminGatewaysRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pagamentos': {
      id: '/_authenticated/admin/pagamentos'
      path: '/pagamentos'
      fullPath: '/admin/pagamentos'
      preLoaderRoute: typeof AuthenticatedAdminPagamentosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transacoes': {
      id: '/_authenticated/admin/transacoes'
      path: '/transacoes'
      fullPath: '/admin/transacoes'
      preLoaderRoute: typeof AuthenticatedAdminTransacoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/cobranca': {
      id: '/api/public/cobranca'
      path: '/api/public/cobranca'
      fullPath: '/api/public/cobranca'
      preLoaderRoute: typeof ApiPublicCobrancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/faturas': {
      id: '/api/public/faturas'
      path: '/api/public/faturas'
      fullPath: '/api/public/faturas'
      preLoaderRoute: typeof ApiPublicFaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/get-logs': {
      id: '/api/public/get-logs'
      path: '/api/public/get-logs'
      fullPath: '/api/public/get-logs'
      preLoaderRoute: typeof ApiPublicGetLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/setup-propix': {
      id: '/api/public/setup-propix'
      path: '/api/public/setup-propix'
      fullPath: '/api/public/setup-propix'
      preLoaderRoute: typeof ApiPublicSetupPropixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-fluxo': {
      id: '/api/public/test-fluxo'
      path: '/api/public/test-fluxo'
      fullPath: '/api/public/test-fluxo'
      preLoaderRoute: typeof ApiPublicTestFluxoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-propix-direto': {
      id: '/api/public/test-propix-direto'
      path: '/api/public/test-propix-direto'
      fullPath: '/api/public/test-propix-direto'
      preLoaderRoute: typeof ApiPublicTestPropixDiretoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-propix-v3': {
      id: '/api/public/test-propix-v3'
      path: '/api/public/test-propix-v3'
      fullPath: '/api/public/test-propix-v3'
      preLoaderRoute: typeof ApiPublicTestPropixV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-secrets': {
      id: '/api/public/test-secrets'
      path: '/api/public/test-secrets'
      fullPath: '/api/public/test-secrets'
      preLoaderRoute: typeof ApiPublicTestSecretsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/$slug': {
      id: '/api/public/webhooks/$slug'
      path: '/api/public/webhooks/$slug'
      fullPath: '/api/public/webhooks/$slug'
      preLoaderRoute: typeof ApiPublicWebhooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminFaturasRoute: typeof AuthenticatedAdminFaturasRoute
  AuthenticatedAdminGatewaysRoute: typeof AuthenticatedAdminGatewaysRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminPagamentosRoute: typeof AuthenticatedAdminPagamentosRoute
  AuthenticatedAdminTransacoesRoute: typeof AuthenticatedAdminTransacoesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminFaturasRoute: AuthenticatedAdminFaturasRoute,
  AuthenticatedAdminGatewaysRoute: AuthenticatedAdminGatewaysRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminPagamentosRoute: AuthenticatedAdminPagamentosRoute,
  AuthenticatedAdminTransacoesRoute: AuthenticatedAdminTransacoesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  FaturaTelefoneRoute: FaturaTelefoneRoute,
  ApiPublicCobrancaRoute: ApiPublicCobrancaRoute,
  ApiPublicFaturasRoute: ApiPublicFaturasRoute,
  ApiPublicGetLogsRoute: ApiPublicGetLogsRoute,
  ApiPublicSetupPropixRoute: ApiPublicSetupPropixRoute,
  ApiPublicTestFluxoRoute: ApiPublicTestFluxoRoute,
  ApiPublicTestPropixDiretoRoute: ApiPublicTestPropixDiretoRoute,
  ApiPublicTestPropixV3Route: ApiPublicTestPropixV3Route,
  ApiPublicTestSecretsRoute: ApiPublicTestSecretsRoute,
  ApiPublicWebhooksSlugRoute: ApiPublicWebhooksSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
